[package]
name = "glue-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
glue-format.workspace = true
glue-resources.workspace = true
libc.workspace = true
thiserror.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
